### ISSUE TITLE
Error when attempting to start cli

### ISSUE THREAD

**Issue by MrMamen** [Hanse/maconomy#8]
module.js:549
    throw err;
    ^

Error: Cannot find module 'mz/fs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/development/maconomy/packages/maconomy-cli/src/index.js:4:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by hanse** [comment]
Did you install via npm/yarn?

**Comment by MrMamen** [comment]
It works now, not sure what happened, but i tried to clone the repo and run ./cli.js directly, perhaps i forgot something.
