### ISSUE TITLE
Error with login

### ISSUE THREAD

**Issue by biohazardxxx** [Hanse/maconomy#9]
hi,

can't manage to get it working (I'm on windows):

```
C:\Users\biohaz>set MACONOMY_RPC_URL=https://URL/DeltekTouch/Maconomy/Time_en_GB_MCS/maconomyshared/backend/RemoteCall.php

C:\Users\biohaz>maconomy login
C:\Users\biohaz\AppData\Roaming\npm\node_modules\maconomy-cli\src\index.js:38
    createAction(async () => {
                       ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\biohaz\AppData\Roaming\npm\node_modules\maconomy-cli\cli.js:3:1)
```

**Comment by hanse** [comment]
Hi. You'll need a recent version of Node.js (8 or later) that supports the async-await syntax.

**Comment by biohazardxxx** [comment]
thanks that worked!
